[versions]
modDevGradleLegacy = "2.0.82"
lombok = "8.7.1"
machete = "1.+"
minecraft = "1.20.1"
forge = "1.20.1-47.3.0"
parchment = "2023.09.03"
registrate = "MC1.20-1.3.3"
anvilLib = "1.0.0+build.29"
jei = "15.3.0.4"
rei = "12.0.648"
emi = "1.1.10+1.20.1"
jade = "11.8.0"
kubejs = "2001.6.3-build.37"
wthit = "forge-8.15.0"
badpackets = "forge-0.4.3"
zeta = "1.0-15.72"
mixinExtras = "0.4.0-beta.2"
clothConfig = "11.1.118"
patchouli = "1.20.1-84-FORGE"
flywheel = "0.6.10-7"
create = "0.5.1.f-27"
annotations = "24.1.0"
mixin = "0.8.5"

[libraries]
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
anvilLib = { group = "dev.anvilcraft.lib", name = "anvillib-forge-1.20.1", version.ref = "anvilLib" }
jeiCommonApi = { group = "mezz.jei", name = "jei-1.20.1-common-api", version.ref = "jei" }
jeiForgeApi = { group = "mezz.jei", name = "jei-1.20.1-forge-api", version.ref = "jei" }
jeiForgeImpl = { group = "mezz.jei", name = "jei-1.20.1-forge", version.ref = "jei" }
reiPlugin = { group = "me.shedaniel", name = "RoughlyEnoughItems-default-plugin-forge", version.ref = "rei" }
reiApi = { group = "me.shedaniel", name = "RoughlyEnoughItems-api-forge", version.ref = "rei" }
reiForge = { group = "me.shedaniel", name = "RoughlyEnoughItems-forge", version.ref = "rei" }
emi = { group = "dev.emi", name = "emi-forge", version.ref = "emi" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
kubejs = { group = "dev.latvian.mods", name = "kubejs-forge", version.ref = "kubejs" }
wthit = { group = "mcp.mobius.waila", name = "wthit", version.ref = "wthit" }
wthitApi = { group = "mcp.mobius.waila", name = "wthit-api", version.ref = "wthit" }
badpackets = { group = "lol.bai", name = "badpackets", version.ref = "badpackets" }
zeta = { group = "org.violetmoon.zeta", name = "Zeta", version.ref = "zeta" }
mixinextrasCommon = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }
mixinextrasForge = { group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinExtras" }
clothConfig = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "clothConfig" }
patchouli = { group = "vazkii.patchouli", name = "Patchouli", version.ref = "patchouli" }
flywheel = { group = "com.jozufozu.flywheel", name = "flywheel-forge-1.20.1", version.ref = "flywheel" }
create = { group = "com.simibubi.create", name = "create-1.20.1", version.ref = "create" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
modDevGradleLegacy = { id = "net.neoforged.moddev.legacyforge", version.ref = "modDevGradleLegacy" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
